import { v4 as uuidv4 } from "uuid";

export const jobs = [
  {
    id: uuidv4(),
    title: "Baking Assistant",
    company: "Janeys Vegan Patisserie",
    location: "Mlolongo, Kenya",
    type: "Full Time",
    applicants: "10",
    salary: "Kshs. 31,000 a month",
    featured: true,
    responsibilities: [
      "Prepare a wide variety of goods such as cakes, cookies, pies, pizza, bread etc. following traditional and modern recipes",
      "Assist in creating new and exciting desserts to renew our menus and engage the interest of customers",
      "Decorate cakes and pastries using different icings, toppings etc. to ensure the presentation will be beautiful and exciting",
      "Monitor stock for baking ingredients such as flour, sugar etc. and make appropriate orders within budget",
      "Maintain quality of material and condition of equipment and devices used for cooking",
      "Must be open to learn and train willing to train other bakers as we grow",
      "Maintain a clean and orderly cooking station and adhere to health and safety standards",
    ],
    qualifications: [
      "Proven experience as pastry chef, baker or relevant role",
      "Attention to detail and creativity",
      "Organising and leadership skills",
      "In depth knowledge of sanitation principles, food preparation and baking techniques and nutrition",
      "Working knowledge of baking with ingredient limitations (pastries that are gluten free, sugarless etc.)",
      "Experience / Certificate in culinary arts, pastry-making, baking or relevant field",
    ],
    about:
      "We are looking for a Baker to assist in preparing a variety of healthy desserts, pastries, cakes or other sweet goods. Your skill in baking high quality treats should be matched by your creativity to develop new amazing tastes and recipes. The ideal candidate will be well-versed in culinary arts with a passion for sweet and delicious creations. They must adhere to health and safety standards to provide clients with the best possible serving.",
  },
  {
    id: uuidv4(),
    title: "Senior ICT Assistant",
    company: "Kenya Animal Genetic Resources Centre (KAGRC)",
    image: "./images/senior-ict-assistant.png",
    location: "Nairobi, Kenya",
    type: "Full Time",
    applicants: "150",
    salary: "Kshs. 24,000 a month",
    featured: false,
    responsibilities: [
      "Providing advice of ICT hardware, software, network and communication devices and equipment.",
      "Participating in acceptance test, supervision and commissioning of ICT systems/equipment.",
      "Providing support and guidance to ICT in the use of ICT equipment and devices.",
      "Participating in implementing programs for safeguarding data integrity of all systems.",
      "Providing for system/application availability through the necessary technical support/upgrades.",
      "Routine installation, configuration servicing, repair and maintenance of computer hardware and network.",
      "Preparing monthly, quarterly and annual maintenance and repair reports.",
      "Participating in committee meetings as appropriate.",
    ],
    qualifications: [
      "Diploma in Computer Science, Information Technology, Information, Communication Technology, or equivalent from a recognized institution.",
      "Two (2) years relevant work experience.",
      "Conversant with software used for semen processing and liquid nitrogen production.",
      "Demonstrated results in work performance.",
      "Fulfilled the requirements of Chapter Six of the Constitution.",
    ],
    about:
      "Kenya Animal Genetic Resources Centre (KAGRC) is a state corporation under the State Department of Crop Development and Agricultural Research, Ministry of Agriculture, Livestock and Fisheries established through Gazette Notice No. L.N. 110 of September, 2011. It has been in operation since 1946 as CAIS and its mandate is to produce, preserve and conserve animal genetic material (semen embryo, tissues and live materials) and rear breeding bulls for provision of high quality disease free semen to meet national demand and for export. KAGRC works in close collaboration with other breeding organizations, societies and individual farms which provide herds for the breeding program such as the Kenya stud book, the Dairy Recording services of Kenya and the Livestock recording centre. KAGRC has five (5) sub-centres in the following counties Ndomba-Kirinyaga, Chuka-Tharaka-Nithi, Sotik-Bomet, Eldoret-Uasin-Gishu and Oljororok-Nyandarua.",
  },
  {
    id: uuidv4(),
    title: "Software Developer - Server Team Leader",
    company: "Food and Agriculture Organization",
    image: "./images/software-developer.png",
    location: "Nairobi, Kenya",
    type: "Contractor",
    applicants: "12",
    salary: "Salary undisclosed",
    featured: false,
    responsibilities: [
      "Database and Application programming",
      "Program application modules for the FAO internal/external usage, both server and client side programming.",
      "Develop various databases using open source programming in a web-based environment, for integration in the FAO database system.",
      " Attend and conduct necessary meetings to plan and program any modules (database, intranet, web site etc.)",
      "Assist in the conceptual development of database driven applications.",
      "Maintain the FAO applications currently in existence and modify/amend whenever necessary.",
      "Develop, deploy, and maintain the BiMS (Beneficiary Information Management System), adding modules as and when required.",
      "Develop, update, and maintain the FAO Somalia website (https://www.fao.org/somalia) in collaboration with Communications department.",
      "All components will be programmed using Open Source software and database systems (MySQL, PHP, XML, JSP, Java, Android, ODBC).",
    ],
    qualifications: [
      "Bachelor's degree in Information Communication Technology (ICT), Computer Science or Computer Engineering.",
      "A minimum of five (5) years' work experience in projects involving database programming and web, mobile and desktop application development, database administration using PHP, Java, Android, and MySQL.",
      "Working knowledge of English.",
      "Kenyan Nationality",
    ],
    about:
      "The key mission of the FAO Representation in Somalia, which is led by FAO Representative (FAOR), is to assist and support the national government to develop policies, strategies and programme aimed at accelerating the Implementation and achievement of the Sustainable Development Goals (SDGs) around FAO's global mandate and Strategic Objectives. More specifically, FAO's response aims to address national needs and priorities in achieving food security, reducing hunger and malnutrition, developing agricultural, fishery and forestry sectors, and ensuring the sustainable use of environmental and natural resources and respond to recurrent emergencies. The current portfolio of activities of the FAO Representation in Somalia includes a wide scope of technical support interventions ranging from policy support through livestock and crop production, to natural resource management, Nutrition, value chain, food security analysis and water and land information management FAO is also implementing several emergency, resilience-building, and development interventions, with the support of its five field offices and close to four hundred staff in partnership with the Federal and State line ministries.",
  },
  {
    id: uuidv4(),
    title: "Corporate Sales Executive",
    company: "Isuzu East Africa Limited",
    image: "./images/isuzu-ea.png",
    location: "Nairobi, Kenya",
    type: "Full Time",
    applicants: "20",
    salary: "Kshs. 65,000 per month",
    featured: false,
    responsibilities: [
      "New business development.",
      "Processing of proposals.",
      "Supporting execution of sales operations processes.",
      "Value and solutions selling.",
      "Customer visits in different regions countrywide in line with defined market segmentation.",
    ],
    qualifications: [
      "Bachelor's degree (Upper second) in Business, Marketing, Engineering or related field.",
      "Five years of working experience.",
      "KCSE Mean grade B+.",
      "Possession of CIM Diploma will be an added advantage.",
    ],
    about:
      "Isuzu East Africa (Isuzu EA) is the leading transport solutions provider in East Africa, selling a wide range of Isuzu vehicles with a solid foundation established by the Isuzu brand's automotive excellence going back over 40 years in the region. The brand has attained strong leadership in this market, selling over 100,000 units since the first vehicle rolled out of its Nairobi assembly plant in 1977. With more than 15 models in its line-up, the Isuzu brand has dominated the new vehicle segment for ten years in a row since 2012, achieving a market share of 45.02% by end of 2021. This is a testimony to customer confidence in its vehicles, transport solutions and excellent aftersales service.",
  },
  {
    id: uuidv4(),
    title: "Transport Infrastructure Engineer",
    company: "European Investment Bank  (EIB)",
    image: "./images/eib.png",
    location: "Nairobi, Kenya",
    type: "Part Time",
    applicants: "18",
    salary: "Salary undisclosed",
    featured: false,
    responsibilities: [
      "Analyse and provide input to the technical, environmental and social as well as financial and economic aspects of project proposals with a view to developing business and early screening of projects.",
      "Where appropriate, interact with project promoters, in close cooperation and with full involvement of the operational departments concerned and local office staff.",
      "Closely follow up on project implementation and monitoring of regional transport operations including relevant reporting.",
      "Advise and follow up on procurement processes and environmental and social safeguards.",
      "Assist in the management of Technical Assistance operations involving the services of external consultants.",
      "Follow and support the development of the transport sector in the East African region and prepare briefings on key issues and strategic developments relevant for the Bank.",
      "Provide input to the preparation of sector related presentations for the Head and/or staff of the Nairobi Office",
      "Where required, and in full coordination with the Head of Office, build relations with key external parties (e.g. EU delegation, international financing institutions, government representatives, local authorities, other institutions).",
      "Where required and in full coordination with the Head of Office/HQ, represent the EIB at events, for example regular sector meetings, conferences or meetings with International Financial Institutions (IFIs).",
    ],
    qualifications: [
      "University degree in engineering in relevant fields for the type of projects concerned in this post.",
      "Additional background in economics would be an advantage.",
      "At least 8 years of experience with planning and implementation of civil engineering project.",
      "Multi-country working experience in particular in the East African region would be an advantage.",
      "Experience in project management, works supervision and or design.",
      "Experience in procurement and safeguard management of International Financial Institutions would be a distinct advantage.",
      "Excellent knowledge of spoken and written English. Good command of French will be an advantage.",
      "Experience in working in the public sector (government or local administration) will be an advantage.",
    ],
    about:
      "The EIB is the European Union's bank. We are the only bank owned by and representing the interests of the European Union Member States. We work closely with other EU institutions to implement EU policy. We are the world's largest multilateral borrower and lender. We provide finance and expertise for sustainable investment projects that contribute to EU policy objectives. More than 90% of our activity is in Europe. But we also are a big investor around the world. How we do it Lending: The vast majority of our financing is through loans, but we also offer guarantees, microfinance, equity investment, etc. Blending: Our support unlocks financing from other sources, particularly from the EU budget. This is blended with loans to form a full financing package. Advising: Lack of finance is often only one barrier to investment. We help with administrative and project management capacity to facilitate investment",
  },
  {
    id: uuidv4(),
    title: "English Content Editor",
    company: "Binance",
    image: "./images/binance.png",
    location: "Nairobi, Kenya",
    type: "Full Time",
    applicants: "80",
    salary: "Salary undisclosed",
    featured: false,
    responsibilities: [
      "Lead internal communications with our business units, product teams and departments to inform and educate users about Binance products and developments.",
      "Review company-wide updates and notices to ensure simple, precise and accurate messaging; to reduce user enquiries, and engage and delight our communities.",
      "Coordinate cross-functionally to respond to internal/external enquiries on those updates.",
      "Work alongside with the lifecycle management team in developing, creating and designing communications across channels, including announcements, email campaigns, inmails and push notifications for different stages of the user journey.",
    ],
    qualifications: [
      "At least 2+ years of experience in content writing, editing, proofreading and publishing.",
      "Native English speaker, with strong English writing and proofreading skills.",
      "Strong internal communications, project management and organizational skills.",
      "Action-driven, results-oriented, attentive to details and enthusiastic, with a strong sense of responsibility and teamwork.",
      "Comfortable working in a global environment.",
      "Solid background in traditional finance industry or the blockchain industry.",
      "Understanding of and experience working with SEO, inbound marketing, email marketing and integrated marketing campaigns is a plus.",
      "Bachelor's degree or above in English, journalism, marketing or related fields.",
      "EU-based would be a plus.",
    ],
    about:
      "We are looking for a great communicator; someone who is self-motivated, can understand complex topics and explain them well via announcements and other owned communication channels. The ideal candidate is in tune with the cryptocurrency industry and passionate about delivering quality content to Binance users; you are versatile, a strong communicator and collaborator, and able to write and edit clear, concise copy on tight deadlines.",
  },
  {
    id: uuidv4(),
    title: "Senior Software and API Integration Engineer",
    company: "CyberBox",
    image: "./images/cyberbox.jpg",
    location: "East Africa",
    type: "Full Time",
    applicants: "124",
    salary: "Kshs. 80,000",
    featured: false,
    responsibilities: [
      "Design, develop, and maintain integration flows using an array of different platforms, APIs, databases, protocols and data formats.",
      "Collaborate with team members to assist in the definition of project scope, deliverables, timelines.",
      "Track and communicate the status of personal deliverable throughout the project lifecycle.",
      "Making sure the data flow is stable, real time and is not missing any events.",
    ],
    qualifications: [
      "5+ years of work experience with APIs, Node.js and Firebase.",
      "Experience in designing and building REST APIs.",
      "Familiar with the tech stack above.",
      "Portfolio that shows your skills (GitHub).",
      "Entrepreneurial spirit and skills to make the ideas into reality.",
      "Precise work and eye for detail, but is pragmatic and able to get things done.",
      "Able to self-organize in a remote-first work environment.",
      "Resourceful approach when facing an issue.",
      "Has strong oral and written communication skills.",
    ],
    about:
      "The Software & API Integrations Engineer is responsible for ownership and delivery of the core functionalities and API integrations that serve as an enterprise data backbone, using an array of different platforms, APIs, databases, protocols and data formats to ensure that the data and the business processes that intersect in the software are as efficient and high fidelity as possible.",
  },
  {
    id: uuidv4(),
    title: "Senior Software Engineer",
    company: "Wikimedia",
    image: "./images/wikimedia.png",
    location: "Nairobi, Kenya",
    type: "Full Time",
    applicants: "380",
    salary: "Kshs. 60,000",
    featured: false,
    responsibilities: [
      "Feature identification and implementation (ex: rate limiting, throttling, etc.)",
      "API Protocols and Architecture Style support guidelines (ex: REST, SOAP, RPC, Kafka, etc.)",
      "Migration of existing APIs to the API Gateway",
      "Integration of the API Gateway into our security strategy",
      "Developing easy-to-use self service pathways for API consumers via our web API portal",
      "Development of a GraphQL data platform that can be leveraged by web and native app feature teams to build consumer-driven products",
      "Assessing and addressing technical risks",
      "Share our values and work in accordance with them",
    ],
    qualifications: [
      "5+ years Expertise in web services and web technologies",
      "Experience building or managing an API Gateway (ideally with Envoy experience)",
      "Demonstrated experience building out API Gateway features including, rate limiting, authentication, throttling, etc.",
      "Experience with API Lifecycle Management",
      "Ability to partner and work closely with internal teams, including developers, engineers, architects, security, and product teams.",
      "Bachelor's degree or equivalent in relevant work experience",
      "Problem-solver with a passion and willingness to learn and dive-deep into technical details",
      "Possess a growth mindset with ability to identify additional skills, knowledge, and/or expertise required and the drive to develop themselves where needed",
      "Familiarity with Envoy API Gateways",
      "Working with on-premise technology stacks",
      "Experience working with microservice architectures",
      "Experience with open-source technology",
      "Experience interacting with free and open-source software projects and communities",
      "Experience editing Wikipedia or contributing to other wiki projects",
      "Remote work experience with a highly distributed team",
    ],
    about:
      "The Wikimedia Foundation is the nonprofit that hosts Wikipedia and our other free knowledge projects. We want to make it easier for everyone to share what they know. To do this, we keep Wikipedia and Wikimedia sites fast, reliable, and available to all. We protect the values and policies that allow free knowledge to thrive. We build new features and tools to make it easy to read, edit, and share from the Wikimedia sites.",
  },
  {
    id: uuidv4(),
    title: "Senior Product Manager",
    company: "Wikimedia",
    image: "./images/wikimedia.png",
    location: "Nairobi, Kenya",
    type: "Part Time",
    applicants: "460",
    salary: "Kshs. 40,000",
    featured: false,
    responsibilities: [
      "Guiding the development of integration of the WMF API Gateway",
      "Feature identification and implementation (ex: rate limiting, throttling, etc.)",
      "API Protocols and Architecture Style support guidelines (ex: REST, SOAP, RPC, Kafka, etc.)",
      "Migration of existing APIs to the API Gateway",
      "Integration of the API Gateway into our security strategy",
      "Defining clear user journeys for API producers and API consumers, both internally and externally",
      "Developing easy-to-use self service pathways for API consumers via our web API portal",
      "Educating stakeholders, supporting API producers, and managing the API lifecycle and API readiness",
      "Development of a GraphQL data platform that can be leveraged by web and native app feature teams to build consumer-driven products",
      "Developing a deep understanding of critical areas of our foundational technology stack, identifying opportunities to improve, extend, and/or leverage existing and new technologies to deliver against our mission and strategy.",
      "Translating product/technical strategy into a roadmap containing well-defined and prioritized user stories and features",
      "Managing incoming requests to engineering, including triaging, clarifying, generating estimates, prioritizing, and managing stakeholder expectations",
      "Uncovering and understanding client needs and translate them into requirements and user stories",
      "Ensuring that requirements are fully understood and implementation plans match expectations",
      "Assessing and addressing technical risks",
      "Working closely with engineering teams to communicate the product vision, clarify use cases and requirements, and resolve questions and issues that arise during development.",
      "Clearly defining success criteria for testing and product acceptance",
      "Use both qualitative and quantitative methods to measure the impact of your work",
      "Serve as a product evangelist and subject matter expert to the technical community",
    ],
    qualifications: [
      "3+ years of experience designing and building APIs for internal and external stakeholders as a technical product manager, software engineer, or equivalent role",
      "Expertise in SOAP and REST web services",
      "Experience building or managing an API Gateway (ideally with Envoy experience)",
      "Experience designing API guidelines and interfaces",
      "A deep understanding of how to integrate API Gateways into a legacy technology stack and the ability to execute this",
      "Direct experience in companies or initiatives that have pulled together disparate products or services into a common experience for customers.",
      "Demonstrated experience building out API Gateway features including, rate limiting, authentication, throttling, etc.",
      "Proven project, communication, and time management skills",
      "Agility and flexibility to work with multiple different teams, projects, and technologies while delivering value and impact",
      "Ability to partner and work closely with internal teams, including developers, engineers, architects, security, and product teams.",
      "Demonstrated experience prioritizing work",
      "Ability to solve complex business problems to maximize value while balancing technical constraints",
      "Ability to draft documentation and visualizations that clarify technical concepts to non-technical audiences and vice-versa",
      "Bachelor's degree or equivalent in relevant work experience",
    ],
    about:
      "The Wikimedia Foundation is the nonprofit that hosts Wikipedia and our other free knowledge projects. We want to make it easier for everyone to share what they know. To do this, we keep Wikipedia and Wikimedia sites fast, reliable, and available to all. We protect the values and policies that allow free knowledge to thrive. We build new features and tools to make it easy to read, edit, and share from the Wikimedia sites. Above all, we support the communities of volunteers around the world who edit, improve, and add knowledge across Wikimedia projects.",
  },
  {
    id: uuidv4(),
    title: "Senior Front-end Web Developer (KYC)",
    company: "Binance",
    image: "./images/binance.png",
    location: "Nairobi, Kenya",
    type: "Full Time",
    applicants: "600",
    salary: "Kshs. 120,000",
    featured: false,
    responsibilities: [
      "Implement new user-facing features in products that have a huge amount of PV every day.",
      "Write client-side code to create super-fast, easy-to-use, web-based applications which include websites for both desktop and mobile browsers, and hybrid in-app pages.",
      "Optimize web applications to maximize speed and scale.",
      "Build libraries and frameworks that support complex web applications, speed up development efficiency and improve code quality.",
      "Contribute creativity and insight to solve both technical and business challenges.",
      "Research and promote new technologies and best practices within the team",
    ],
    qualifications: [
      "3+ years of experience developing production software.",
      "Advanced knowledge of TypeScript + React.",
      "Experience with modern web technologies such as Webpack, Next.js, Redux, styled-components, or similar.",
      "Proven track record of delivering well-tested, high-quality, maintainable projects.",
      "Great cross-team communication skills.",
      "Self-managed, proactive work style. Ability to perform at a high level in a fast-paced environment.",
      "Blockchain-related industry experience is a plus.",
      "Experience in managing a distributed team of engineers as a plus.",
    ],
    about:
      "Binance is an online exchange where users can trade cryptocurrencies. It supports most commonly traded cryptocurrencies. Binance provides a crypto wallet for traders to store their electronic funds. The exchange also has supporting services for users to earn interest or transact using cryptocurrencies.",
  },
  {
    id: uuidv4(),
    title: "Junior API Developer",
    company: "Gebeya Limited",
    image: "./images/gebeya.png",
    location: "Nairobi, Kenya",
    type: "Full Time",
    applicants: "180",
    salary: "Ksh. 80,000",
    featured: false,
    responsibilities: [
      "Deliver and deploy a working web service (including the source code) to the Dev environment based on the business requirements.",
      "Deliver all documentations related to the web service delivered.",
      "Develop and designing relevant code on project needs.",
      "Mentoring junior developers.",
      "Create test driven environment for relevant projects.",
    ],
    qualifications: [
      "Bachelor's degree or equivalent experience in Computer Science 4-6 years of industry experience.",
      "Technical depth across multiple languages.",
      "Able to meet deadlines.",
      "Leadership experience.",
      "Strong communications skills.",
    ],
    about:
      "Gebeya Inc. is a Pan-African online Freelance Talent Marketplace headquartered in Addis Ababa, Ethiopia. The company aims to become an active contributor to Africa's digital transformation and build a booming Africa through leveraging continental and global job opportunities for African talent.",
  },
];
